"use strict";

export const REQUEST_TOPICS = "REQUEST_TOPICS";

export const RECEIVE_TOPICS = "RECEIVE_TOPICS";

export const REQUEST_TOPIC = "REQUEST_TOPIC";

export const RECEIVE_TOPIC = "RECEIVE_TOPIC";

export const REQUEST_USERINFO = "REQUEST_USERINFO";

export const RECEIVE_USERINFO = "RECEIVE_USERINFO";